### PR TITLE
Additional changes to support Thunderbird 57

### PR DESCRIPTION
**Pull request by firetray-updates**

### CODE REVIEW

**Comment by firetray-updates** [comment]
Hi, I recently moved to Thunderbird 60 and found that sadly FireTray no longer works.

I've come across your fork and fixed the error I saw in the console. The preferences are still broken, so you either use the config editor manually or upgrade from a previous installation. Not ideal, but it's enough for me for now.

**Comment by firetray-updates** [comment]
Well, all I needed to fix the preferences was a simple line.

~There's still `nsIDOMXPathResult` that needs to be replaced with something else, but the preferences at least work now.~

**Comment by mfreeman-xtivia** [comment]
Is this available as an installable .xpi file somewhere? I would LOVE to use this for my TB 60 on Windows but not sure I have the build environment needed?

**Comment by CubicF** [comment]
> 
> 
> Is this available as an installable .xpi file somewhere? I would LOVE to use this for my TB 60 on Windows but not sure I have the build environment needed?

No, but you can find installable .xpi files here: https://github.com/Ximi1970/FireTray/releases

**Comment by mfreeman-xtivia** [comment]
Works like an absolute champ on my Windows 10.

I cannot tell you how AWESOME it is to have FireTray back. Thank you.

**Pull request merged**
